### ISSUE TITLE
[FR] Dosimeter

### ISSUE THREAD

**Issue by FalcoGer** [nmrr/flipperzero-geigercounter#1]
Would it be possible to add some option to input (and save) the characteristics of the tube, and/or have some presets, like for the [J305Br](https://www.jameco.com/Jameco/Products/ProdDS/2210141.pdf) to calculate Sv/h and total Sv since start/reset?

Also an average count over a configurable time span + total since reset would be nice.

More Refs
- https://hps.org/publicinformation/ate/q4148.html

**Comment by nmrr** [comment]
Hello,

Thank you for your suggestions. I've just added μSv/h and mSv/y. Some nice features have been planned.
