### ISSUE TITLE
Error after compiling and launch app

### ISSUE THREAD

**Issue by danidemis** [nmrr/flipperzero-geigercounter#13]
Hi, 

I have a self-made geiger counter which uses a different probe, an SBM20. I have seen the instructions for doing the build, changed the value of the correction index (from 0.0081 to 0.00926) related to the probe in the file flipper_geiger.c , did the build by doing a clone of the latest RM repository (version currently installed on the flipper as well) and even though the build finishes successfully, when I do to open the app the FZ crash and it gives me the following error:

![Photo43724387](https://github.com/nmrr/flipperzero-geigercounter/assets/7957600/a971b9f5-ac62-4bfc-b13f-449985f8868e)

I would like to say that with the version downloaded directly from your repository, that is, with the FAP you provide and with RM's FAP the app works as well as reading data from the geiger counter.

I'm using RM firmware version [RM0305-1134-0.99.1-46c6775](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/RM0305-1134-0.99.1-46c6775) 

I'm new to build apps for FZ, maybe I'm do something wrong.

**Comment by nmrr** [comment]
Now it's working

**Comment by danidemis** [comment]
Hi, the problem persists, i have re-downloaded the repo and re-launched the compilation, it still gives me the same error.... I also synchronize the RM firmware local repo, nothing to do..

Have you some hint to build it without problem?
Thanks

**Comment by nmrr** [comment]
Hello,

Have you tried with **371cc84** commit ? I uploaded wrong file when I closed your issue. Now it should be good

**Comment by nmrr** [comment]
Now it's working, sorry for the delay
