### ISSUE TITLE
Flipper Zero crashes upon opening app 

### ISSUE THREAD

**Issue by Poisonfox69** [nmrr/flipperzero-geigercounter#14]
When I open Geiger Counter, the Flipper crashes and "furi_check failed" is displayed. All apps and firmware up to date as of 11 March 2024.

**Comment by nmrr** [comment]
Now it's working

**Comment by Poisonfox69** [comment]
> Now it's working

Should I update anything to get it to work? It still crashes when I do it.

**Comment by nmrr** [comment]
Have you rebuild the app with the last commit ? This app works with the last firmware

**Comment by Poisonfox69** [comment]
> Have you rebuild the app with the last commit ? This app works with the last firmware

Yes, it still crashes. I tried all firmware as well to make sure. It's very strange.

**Comment by nmrr** [comment]
Very very strange. I've just tried again on my F0 and the app crashed. I removed **furi_hal_gpio_** functions and the app started without tick measure function. I added again  **furi_hal_gpio_** functions and now the app is working. I think there is a bug inside the firmware. I'll investigate

**Comment by Poisonfox69** [comment]
Hopefully it's back up soon. Thanks guys!

**Comment by kojak1973** [comment]
I struggle with the same issue. Hope you will find a fix, soon.
THX for your investigation in this!

**Comment by nmrr** [comment]
I'll wait the next release of the firmware. I'm pretty sure there is a bug inside the current firmware

**Comment by Poisonfox69** [comment]
Has anyone tried any alternate firmware for the Flipper?

**Comment by nmrr** [comment]
Now it's working, sorry for the delay
