### ISSUE TITLE
Jack Out Port cable color to A7 GPIO? 

### ISSUE THREAD

**Issue by drnemo1** [nmrr/flipperzero-geigercounter#2]
What wire or color of wire do you use off the PC/Headphone cable to the Jack Out Port to A7 GPIO? Mine has three wires- red, black and green.

**Comment by nmrr** [comment]
Hello,

Black is usually used for the ground (sleeve on the schematic). You can use a multimeter to be sure or simply test other wires. GPIO pins have an internal resistance so there is no risk.

<p align="left"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Tip-Ring-Sleeve_plug.svg/302px-Tip-Ring-Sleeve_plug.svg.png" width=20% height=20%></p>
