### ISSUE TITLE
Jack to GPIO connection

### ISSUE THREAD

**Issue by Kuronons** [nmrr/flipperzero-geigercounter#3]
Hey ! Very nice project. Just wondering :

_You can use jack out port instead._

Could you please elaborate on the how-to connect a 3 wires jack cable to a 1 single wire GPIO cable ?

**Comment by Kuronons** [comment]
I orginally soldered a dupont wire in a mono 3.5 jack adapter. Thought it worked but realized it didn't as I had weird high cpm values.

-> Finally soldered a dupont wire on the ring-wire of a "stereo" jack to get it to work properly.

Also jumper on P1. (was put on test by default)

![Geiger2](https://user-images.githubusercontent.com/110337784/221391194-d3a5a808-3eb9-4a7a-8545-05d0783bc481.jpg)

**Comment by Kuronons** [comment]
![Geiger](https://user-images.githubusercontent.com/110337784/221385797-15f0f06e-0a20-4694-bcf8-908aa9d71ab0.jpg)

**Comment by nmrr** [comment]
Hello,

I've just edited the readme. A few days ago someone asked the same question.
