### ISSUE TITLE
ValueMutex

### ISSUE THREAD

**Issue by RogueMaster** [nmrr/flipperzero-geigercounter#5]
Could you refactor without the valuemutex? It has been removed from all firmware's making your changes stop working for all firmware's.

**Comment by RogueMaster** [comment]
Here it is already refactored... https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/0173240ca9f64022392e1edde08a71f83a66057a/applications/external/geigercounter/flipper_geiger.c

**Comment by nmrr** [comment]
Thank you for the information. I'll apply your modification & I'll update Pong game.
