### ISSUE TITLE
GPIO-in bypass possible

### ISSUE THREAD

**Issue by BlackPropaganda** [nmrr/flipperzero-geigercounter#6]
I recently came across one of the boards and I didn't have the hardware to sacrifice the provided 3.5mm audio jack so I decided to play around with the board to see if there was a place I could solder and get the same data from the board. I found one and I got an accurate read. Would you like to see how I did it?

**Comment by luppano** [comment]
Yes please !

**Comment by nmrr** [comment]
Hello, you can solder a jumper wire at output of opamp if you don't want to cut audio jack :

<p align="left"><img src="https://i.imgur.com/vDow9NL.png" width=60% height=60%></p>

Don't use red led signal due to the presence of monostable circuit (you will lose precision)
