### ISSUE TITLE
No signal on the jack or op-amp out 2, board clicking and seemingly working otherwise.

### ISSUE THREAD

**Issue by luppano** [nmrr/flipperzero-geigercounter#7]
I got the board working, soldered the tip and ring wires of a jack together and to a jumper cable plugged in the A7 port. The A4 to A7 test is working, the board is also making noise and the LED blinking, the continuity is okay, but the Flipper only reads something when plugging/unplugging the jack. Nothing when the board picks up actual radiation cascades. What could be the issue ? Can the Flipper not be sensitive enough to pick up the signal even via the audio jack and op-amp ? Plugging in a headset, I dont hear any clics, only some low white noise, for a few seconds after plugging in. I also got nothing by shunting a jumper cable directly from the op-amp "out 2" to the Flipper A7. Could I've been delivered a dead op-amp ? How can I test that ? I'm very new to this. Thank you.

**Comment by nmrr** [comment]
Have you a black jumper on **P100** ? You can use **test** jumper if you want to keep click sound from the buzzer

**Comment by nmrr** [comment]
I'm going to close this issue, don't hesitate to reopen this issue if you still have problem with the board
