### ISSUE TITLE
Flipper crashed and was rebooted - furi_check failed

### ISSUE THREAD

**Issue by dev-null2019** [nmrr/flipperzero-geigercounter#9]
Hello!
Does not work with Roguemaster FW (RM0602-0936-0.83.2-8927831)

Flipper reboots after app launch with "Flipper crashed and was rebooted - furi_check failed"

Before I take a deep dive into it - anyone else had this problem before?

Regards

**Comment by nmrr** [comment]
Hello,

Have you compiled the project with roguemaster SDK or have you used the .fap file inside the repo ?

**Comment by devaudio** [comment]
I get the same thing, I have compiled it with rougemaster SDK --


```
 ✘ sclark@mac-mini  ~/workspace/src/flipperzero-firmware-wPlugins   420  ./fbt launch_app APPSRC=applications_user/flipper_geiger

fbt: warning: Folder /Volumes/External/sclark/workspace/src/flipperzero-firmware-wPlugins/applications_user/flipperzero-geigercounter: manifest application.fam is missing
LoadAppManifest, line 33, in file "/Volumes/External/sclark/workspace/src/flipperzero-firmware-wPlugins/scripts/fbt_tools/fbt_apps.py"
	SDKCHK	firmware/targets/f7/api_symbols.csv
API version 29.0 is up to date
python3 "./scripts/runfap.py" -s build/f7-firmware-C/.extapps/flipper_geiger.fap -t /ext/apps/Tools/flipper_geiger.fap
	APPCHK	build/f7-firmware-C/.extapps/flipper_geiger.fap
2023-06-07 18:54:43,607 [INFO] Using flip_Int4k3n on /dev/cu.usbmodemflip_Int4k3n1
2023-06-07 18:54:43,657 [INFO] Installing "build/f7-firmware-C/.extapps/flipper_geiger.fap" to /ext/apps/Tools/flipper_geiger.fap
2023-06-07 18:54:43,683 [INFO] Launching app: "Applications" /ext/apps/Tools/flipper_geiger.fap
```


but get f_uri error, same as first guy

**Comment by nmrr** [comment]
Thank you. Something had obviously changed in the firmware.
I'll do the necessary to correct my app

**Comment by sboger** [comment]
Same for me with OEM firmware.

Flipper with fresh install of latest OEM firmware 0.84.2

> s@balance:~/flipperzero-geigercounter/flipper_geiger$ ufbt clean && ufbt launch
> 02:43:45.591 [I] Cleaning SDK state in /home/s/.ufbt/current
> 02:43:45.600 [I] Done
> 02:43:45.654 [E] No previous SDK state was found, fetching latest release
> 02:43:45.654 [I] Deploying SDK for f7
> 02:43:45.654 [I] Fetching version info for UpdateChannel.RELEASE from https://update.flipperzero.one/firmware/directory.json
> 02:43:46.059 [I] Using version: 0.84.2
> 02:43:46.060 [I] uFBT SDK dir: /home/s/.ufbt/current
> 02:43:47.932 [I] Deploying SDK
> 02:43:48.116 [I] SDK deployed.
> scons: Entering directory '/home/s/.ufbt/current/scripts/ufbt'
> python3 "/home/s/.ufbt/current/scripts/runfap.py" -s /home/s/.ufbt/build/flipper_geiger.fap -t /ext/apps/Tools/flipper_geiger.fap
> 	APPCHK	/home/s/.ufbt/build/flipper_geiger.fap
> 		Target: 7, API: 28.2
> 2023-06-08 02:43:48,267 [INFO] Using flip_Wogclin on /dev/ttyACM2
> 2023-06-08 02:43:48,318 [INFO] Installing "/home/s/.ufbt/build/flipper_geiger.fap" to /ext/apps/Tools/flipper_geiger.fap
> 2023-06-08 02:43:48,327 [INFO] Sending "/home/s/.ufbt/build/flipper_geiger.fap" to "/ext/apps/Tools/flipper_geiger.fap"
> 100%, chunk 1 of 1 @ 54.70 kb/s
> 2023-06-08 02:43:48,449 [INFO] Launching app: "Applications" /ext/apps/Tools/flipper_geiger.fap
>

**Comment by dev-null2019** [comment]
I compiled it with the Roguemaster SDK.

**Comment by devaudio** [comment]
I am watching this closely, so that I can measure how radioactive my cat is:

[https://www.instagram.com/p/CtOw12iOWuR/?igshid=MzRlODBiNWFlZA==](Radioactive Kitty)

**Comment by nmrr** [comment]
The bug has just been fixed

@devaudio, I havn't instagran, can you upload your measure elsewhere ?

**Comment by sboger** [comment]
Confirmed good on stock 0.84.2.

Thank you!

**Comment by devaudio** [comment]
confirmed that it's good -- here is a better link to the kitty

https://youtube.com/shorts/JQB2jvY1oZ0?feature=share

**Comment by nmrr** [comment]
That's incredible ! Thank you. Your cat will be radioactive for at least two month (half life of Iodine-131 is 8 days).

**Comment by Neorichi** [comment]
I have the same problem with Roguemaster v0.86.1
Thanks

**Comment by RogueMaster** [comment]
> I have the same problem with Roguemaster v0.86.1

Did you mean 0.86.2 or are you on an old version? Originally you said 0.84.1... Please re-test on latest version that will come out today

**Comment by Neorichi** [comment]
> > I have the same problem with Roguemaster v0.86.1
> 
> Did you mean 0.86.2 or are you on an old version? Originally you said 0.84.1... Please re-test on latest version that will come out today

i said 0.86.1, yes :)
![image](https://github.com/nmrr/flipperzero-geigercounter/assets/3147619/41c7d3c6-283e-4e6d-aa30-86691375f3d6)

**Comment by nmrr** [comment]
On the official FW 0.81.1 it's works well. Have you compiled the program or have you used the .fap file of the repo ? If you are using roguemaster FW, you have to compile the app with roguemaster toolchain, not official toolchain

**Comment by Neorichi** [comment]
> 

Perfect. Now it is working fine. thanks a lot
